### ISSUE TITLE
Thank you for the repo and some questions

### ISSUE THREAD

**Issue by sovit-123** [uvipen/SSD-pytorch#1]
First of all, thanks for the repo. Was trying to find something like this. It will help me a lot.
There are a few questions that I want to ask.
1. The trained model that you are providing, is trained for 50 epochs, right?
2. Also, any possibility to get trained weight for the SSDLite version anytime soon?

Thanks again.

**Comment by uvipen** [comment]
1. I trained for 54 epochs.
2. I will try to upload it next week. Thanks for your interest
