### ISSUE TITLE
training with a custom dataset

### ISSUE THREAD

**Issue by abdo-ameen** [uvipen/SSD-pytorch#2]
I have two questions, how can I use this code to train the SSD with my own custom dataset? and after finishing the training process, how can I use the model for inference tasks on real-time camera applications?
thank you for simplifying the SSD idea, I'm a beginner and I'm finding the existing implementations really complicated.

**Comment by uvipen** [comment]
Hi,
1. You need to write your own dataloader, based on mine for COCO
2. If you need to run it in real device, I think you need to convert the trained model to onnx or tensorrt. Unfortunately I cant not provide detail step for it.
Bests,
